<!-- 
<!DOCTYPE html>
<html>
<head>
    <title>Subscriptions PDF</title>
    <style>
        body {
            font-family: 'DejaVu Sans', Arial, Helvetica, sans-serif;
            color: #222;
            margin: 0;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h2 {
            margin: 0;
            font-size: 28px;
            color: #2c3e50;
            letter-spacing: 1px;
        }
        .header p {
            font-size: 9px;
            color: #555;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            background: #fff;
            box-shadow: 0 2px 8px rgba(44,62,80,0.07);
        }
        th {
            background: #2c3e50;
            color: #fff;
            font-size: 12px;
            font-weight: 600;
            padding: 12px 8px;
            border: 1px solid #2c3e50;
            text-align: left;
        }
        td {
            padding: 10px 8px;
            border: 1px solid #e1e1e1;
            font-size: 10px;
        }
        tr:nth-child(even) {
            background: #f2f6fa;
        }
        tr:hover td {
            background: #eaf3fb;
        }
        .footer {
            margin-top: 40px;
            text-align: right;
            font-size: 13px;
            color: #888;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>Subscriptions List</h2>
        <p>{{ date('d M Y, h:i A') }}</p>
    </div>
    <table>
        <thead>
            <tr>
                @foreach($columns as $col)
                    <th>{{ ucwords(str_replace('_', ' ', $col)) }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($data as $row)
                <tr>
                    @foreach($columns as $col)
                        <td>{{ $row[$col] ?? '-' }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($columns) }}" style="text-align:center;">No data found</td>
                </tr>
            @endforelse
        </tbody>
    </table>
    <div class="footer">
        Generated by TIHD &mdash; {{ date('d M Y') }}
    </div>
</body>
</html> -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Subscriptions PDF</title>
    <style>
        body {
            font-family: 'DejaVu Sans', Arial, Helvetica, sans-serif;
            color: #6B6B6B;
            font-size: 16px;
            margin: 0;
        }
        h1, h2, h3, h4, h5, h6 {
            margin: 0;
            color: #010A0F;
            font-weight: 500;
        }
        p {
            margin: 0;
        }
        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 30px;
        }
        .header-logo {
            /* এখানে তুমি চাইলে লোগো এর Blade include বা img ট্যাগ রাখতে পারো */
            /* উদাহরণ: */
            /* <img src="logo_url" alt="Logo" height="40"> */
        }
        .header-info {
            text-align: right;
            color: #010A0F;
            font-size: 14px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            border: 1px solid #CCCCCC;
            border-radius: 6px;
        }
        thead {
            background-color: #F2F2F2;
        }
        th {
            color: #010A0F;
            font-weight: 600;
            padding: 10px;
            border: 1px solid #CCCCCC;
            text-align: left;
        }
        td {
            padding: 10px;
            border: 1px solid #CCCCCC;
            font-size: 14px;
        }
        tr:nth-child(even) td {
            background-color: #fafafa;
        }
        .footer {
            margin-top: 40px;
            text-align: right;
            font-size: 13px;
            color: #888;
        }
    </style>
</head>
<body>

    <div class="header">
        <div class="header-logo">
            {{-- লোগো এখানে include করো --}}
            @include('frontend::components.partials.logo')
        </div>
        <div class="header-info">
            <p>{{ date('d M Y, h:i A') }}</p>
            <p><strong>Subscriptions List</strong></p>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                @foreach($columns as $col)
                    <th>{{ ucwords(str_replace('_', ' ', $col)) }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($data as $row)
                <tr>
                    @foreach($columns as $col)
                        <td>{{ $row[$col] ?? '-' }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($columns) }}" style="text-align:center;">No data found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by TIHD &mdash; {{ date('d M Y') }}
    </div>

</body>
</html>
