
<!DOCTYPE html>
<html>
<head>
    <title>Subscriptions PDF</title>
    <style>
        body {
            font-family: 'DejaVu Sans', Arial, Helvetica, sans-serif;
            color: #222;
            margin: 0;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h2 {
            margin: 0;
            font-size: 28px;
            color: #2c3e50;
            letter-spacing: 1px;
        }
        .header p {
            font-size: 9px;
            color: #555;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            background: #fff;
            box-shadow: 0 2px 8px rgba(44,62,80,0.07);
        }
        th {
            background: #2c3e50;
            color: #fff;
            font-size: 12px;
            font-weight: 600;
            padding: 12px 8px;
            border: 1px solid #2c3e50;
            text-align: left;
        }
        td {
            padding: 10px 8px;
            border: 1px solid #e1e1e1;
            font-size: 10px;
        }
        tr:nth-child(even) {
            background: #f2f6fa;
        }
        tr:hover td {
            background: #eaf3fb;
        }
        .footer {
            margin-top: 40px;
            text-align: right;
            font-size: 13px;
            color: #888;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>Subscriptions List</h2>
        <p>{{ date('d M Y, h:i A') }}</p>
    </div>
    <table>
        <thead>
            <tr>
                @foreach($columns as $col)
                    <th>{{ ucwords(str_replace('_', ' ', $col)) }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($data as $row)
                <tr>
                    @foreach($columns as $col)
                        <td>{{ $row[$col] ?? '-' }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($columns) }}" style="text-align:center;">No data found</td>
                </tr>
            @endforelse
        </tbody>
    </table>
    <div class="footer">
        Generated by TIHD &mdash; {{ date('d M Y') }}
    </div>
</body>
</html>